#! /usr/bin/env escript
%%! -K true -smp enable -pa ../ebin

main([ConnectTo, MessageSizeStr, MessageCountStr]) ->
  {MessageSize, _} = string:to_integer(MessageSizeStr),
  {MessageCount, _} = string:to_integer(MessageCountStr),
  {ok, Context} = zmq:init(1),
  {ok, Socket} = zmq:socket(Context, pub),
  zmq:connect(Socket, ConnectTo),
  Msg = list_to_binary(lists:duplicate(MessageSize, 0)),
  [zmq:send(Socket, Msg) || _I <- lists:seq(1, MessageCount)],
  zmq:term(Context)
;
main(_) ->
  io:format("Usage: remote_thr \"<zmq endpoint>\" <size> <count>~n")
.
